name: Publish Plugin to Rubygems.org

on:
  push:
    branches:
      - master

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jsvd/logstash-plugin-actions@master
  publish:
    needs: verify_version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jsvd/logstash-plugin-action-publish@master
