name: Verify presence of version bump

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jsvd/logstash-plugin-actions@master
