name: Verify presence of version bump

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - uses: jsvd/logstash-plugin-actions@master
